# Generated by Django 4.1.13 on 2024-08-17 13:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoobject',
            name='user',
            field=models.CharField(max_length=250, verbose_name=django.contrib.auth.models.User),
        ),
    ]
